=== api-evangelist/github/json-schema/github-issues-api-global-hook-2-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/github/refs/heads/main/json-schema/github-issues-api-global-hook-2-schema.json",
  "title": "global-hook-2",
  "description": "global-hook-2 from GitHub API",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "example": "User"
    },
    "id": {
      "type": "integer",
      "example": 42
    },
    "name": {
      "type": "string",
      "example": "octocat"
    },
    "active": {
      "type": "boolean",
      "example": true
    },
    "events": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "config": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "content_type": {
          "type": "string"
        },
        "insecure_ssl": {
          "type": "string"
        }
      }
    },
    "updated_at": {
      "type": "string",
      "example": "2026-04-17T12:00:00Z"
    },
    "created_at": {
      "type": "string",
      "example": "2026-04-17T12:00:00Z"
    },
    "url": {
      "type": "string",
      "example": "https://api.github.com/repos/octocat/Hello-World"
    },
    "ping_url": {
      "type": "string",
      "example": "https://api.github.com/repos/octocat/Hello-World"
    }
  }
}

=== api-evangelist/github/examples/github-auth-api-global-hook-example.json
{
  "type": "User",
  "id": 42,
  "name": "octocat",
  "active": true,
  "events": [
    "example_value"
  ],
  "config": {
    "url": "https://api.github.com/repos/octocat/Hello-World",
    "content_type": "example_value",
    "insecure_ssl": "example_value",
    "secret": "example_value"
  },
  "updated_at": "2026-04-17T12:00:00Z",
  "created_at": "2026-04-17T12:00:00Z",
  "url": "https://api.github.com/repos/octocat/Hello-World",
  "ping_url": "https://api.github.com/repos/octocat/Hello-World"
}
